version: "3.7"
services:
  nginx:
    build:
      context: .
      dockerfile: dockerfiles/nginx.dockerfile
    image: cray-nginx:latest
    container_name: cray-nginx
    ports:
      - "8001:8080"
    depends_on: 
      - laravel
      - db
  laravel:
    build:
      context: .
      dockerfile: dockerfiles/laravel.dockerfile
    container_name: cray-laravel
    image: cray-laravel:latest
    restart: unless-stopped
    tty: true
  db:
    image: mysql:8
    container_name: cray-mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "6001:3306"
    depends_on:
      - laravel
    environment: 
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=laravel
  redis:
    image: redis:5
    container_name: cray-redis
    ports:
      - "3001:6379"
